### ISSUE TITLE
Сделать ArraySerializableInterface для Exceptions.

### ISSUE THREAD

**Issue by rollsover** [egal/framework-php-package#168]

**Comment by PolinaFarlie** [comment]
**Проблема:** создается массив грузов, часть из них с ошибкой. Мы не можем вывести ошибку потому что ошибка это один груз создан неправильно. С массивом она не дает информации - где именно ошибка, в каком грузе?
Сейчас - костыль. Данные выводятся не как ошибка, а экшен резалт, статус 200, где уже перечисляется в каких грузах ошибка.
**Требования**
По реализации удобнее трейт, чтобы можно было включать и отключать, но еще лучше, если решение будет жестко зашито в коробку и работать всегда, чтобы фронты всегда получали данные в одинаковом виде.
отключать можно в случае если нужно отдавать api на сторону, тогда нужно предоставить удобный именно им вид ошибок - такой есть кейс отключения.
В http-ответе эти данные должны быть в error-message но не в строку а отдельными полями. Подробные описания ошибок в каждом объекте не нужны.
Из коробки ребята ожидают формирование, вид объекта.
Бэк должен перечислять в ошибке в каких объектах ошибка, а фронт красиво выводить в ошибку со списком неправильных объектов.

**Решение**
Мы добавим подключаемый интерфейс для использования внутри эксепшенов с объектами.
Зашьем в коробку проверку, что если есть интерфейс, то вызываем получение объектов для записи в ответ. Если объекты не пустые, то подставляем этот ответ.
По виду ошибки мы думаем сделать по аналогии с экшен резалт:
data {...перечисление объектов...}
message: "{текст ошибки}"
В тексте ошибки, который выводится фронтом - перечисление объектов, в которых ошибка. Но просто перечисление, без указания вида ошибки.

**Comment by rollsover** [comment]
@PolinaFarlie Где PR на документацию?

**Comment by annstgn** [comment]
> @PolinaFarlie Где PR на документацию?

https://github.com/egal/egal-docs/pull/88

**Comment by rollsover** [comment]
https://github.com/egal/egal-docs/pull/88#discussion_r763630033
