### ISSUE TITLE
Дырка в безопасности: Можно подобрать содержание данных через actionUpdate, потому, что у нас все проверки.

### ISSUE THREAD

**Issue by rollsover** [egal/framework-php-package#183]
В проекте доступ к endpoint проверяется на событии updatingWithAction. Поскольку данное событие срабатывает только при изменении атрибутов, а при передаче тех же самых атрибутов, возвращается ответ с кодом 200, то есть возможность подобрать данные, хранимые в БД. После реализации задачи команда SPOT перенесет проверку на event retrievedWithAction.

**Comment by rollsover** [comment]
Нужно вернуть retrivedWithAction

**Comment by annstgn** [comment]
Посмотрела, если ставить ограничение по роли, от все ок, никаких полей не видно, даже если не обновлять атрибуты. Надо уточнить у спот команды, скорее всего свои кастомные проверки доступа стоят на updating (а без изменения атрибутов выполняется только saving). 
Если вернуть retrivedWithAction, то по такой логике и на кастомные действия события retrivedWithAction/updatedWithAction и т.д. должны срабатывать при получении объектов/ обновлении объектов и т.д.?
Или события WithAction вызываются только по endpoint-ам из коробки?

**Comment by annstgn** [comment]
Или сделать отдельно стандартные события при вызове через HTTP и события при вызове конкретных endpoint-ов?

**Comment by annstgn** [comment]
Нужно, чтобы withAction события срабатывали как стандартные, но только при триггере через HTTP. Даже на уникальных endpoint (?)

**Comment by rollsover** [comment]
Добавь описание, почему дырка то?

**Comment by annstgn** [comment]
> Добавь описание, почему дырка то?

Обновила описание
