### ISSUE TITLE
Неудобно обрабатывать response при межсервисном общении.

### ISSUE THREAD

**Issue by annstgn** [egal/framework-php-package#188]
После getResponse() приходится самостоятельно проверять код ответа и в зависимости от его значения получать соответствующую составляющую ответа (ошибку или результат).

**Comment by PolinaFarlie** [comment]
Сейчас у нас есть объект ответа. У него мы можем вызвать метод получения кода ответа, метод получения ошибки и метод получения результата. 
Отправляется запрос, получен ответ и нужно вернуть его клиенту. Для этого надо проверить код ответа и вызвать либо получение ошибки, либо получение результата. 
А лучше было бы вызывать один метод для передачи ответа клиенту.
