### ISSUE TITLE
Обернуть передаваемые параметры в "attributes" в '/upload' запросах

### ISSUE THREAD

**Issue by novkri** [egal/framework-php-package#233]
Запрос на загрузку файла сейчас принимает параметры: 
````json
{
       "file_basename":  "example.txt",
       "contents": "Contents of file"
}
````
Чтобы отправлять запрос через егаловский экшен на клиенте, нужен вид:
````json
{
    "attributes": {
           "file_basename":  "example.txt",
           "contents": "Contents of file"
     }
}
````

upd: аналогичный вид параметров нужен для запросов "/createMultipartUpload",  "/uploadPart", "/completeMultipartUpload"

**Comment by novkri** [comment]
все ок, все работает

**Comment by annstgn** [comment]
Неправильно передавать параметры данных ендпоинтов с ключом attributes
